// Display translations only. English IDs and persisted names remain canonical.
const amharic = {
  "English": "English", "Language": "ቋንቋ", "Display only, on this device.": "ለዚህ መሣሪያ ማሳያ ብቻ።",
  "Transactions": "ግብይቶች", "Balance": "ቀሪ ሂሳብ", "Construction": "ግንባታ", "Settings": "ቅንብሮች",
  "Dawit": "ዳዊት", "Mihret": "ምሕረት", "Asnake": "አስናቀ", "Yiss": "ይስ", "Enku": "እንቁ", "Dawit Enku": "ዳዊት እንቁ",
  "All": "ሁሉም", "Filter transactions": "ግብይቶችን አጣራ", "Withdraw": "ወጪ", "Withdrawal": "ወጪ", "Deposit": "ገቢ",
  "ID": "ቁጥር", "Person": "ሰው", "Amount": "መጠን", "Date / Time": "ቀን / ሰዓት", "Reference no": "የግብይት ቁጥር",
  "Reference": "የግብይት ቁጥር", "Narrative": "ማብራሪያ", "More": "ተጨማሪ", "Materials": "ቁሳቁስ", "Null": "ያልተመደበ", "Unassigned": "ያልተመደበ",
  "Swipe to see more": "ተጨማሪ ለማየት ወደ ጎን ያንሸራትቱ", "Table Total": "የሰንጠረዡ ድምር", "Send table total to calculator": "ድምሩን ወደ ማስያ ላክ",
  "Main navigation": "ዋና ማውጫ", "Bank of Abyssinia": "አቢሲኒያ ባንክ", "bank logo": "የባንኩ አርማ", "Bank Logo": "የባንኩ አርማ",
  "Bank Tracker": "የባንክ መከታተያ", "Bank tracker": "የባንክ መከታተያ", "Bank Tracker · Version": "የባንክ መከታተያ · ስሪት",
  "Add transaction": "ግብይት ጨምር", "Edit": "አስተካክል", "Delete": "ሰርዝ", "Close": "ዝጋ", "Cancel": "ተው", "Continue": "ቀጥል",
  "Save": "አስቀምጥ", "Saving…": "በማስቀመጥ ላይ…", "Saving...": "በማስቀመጥ ላይ…", "Saved": "ተቀምጧል", "Retry": "እንደገና ሞክር",
  "Add": "ጨምር", "Remove": "አስወግድ", "Remove person": "ሰውን አስወግድ", "Confirm add": "ማከሉን አረጋግጥ", "Back": "ተመለስ",
  "Add receipt": "ደረሰኝ ጨምር", "Choose how to add your receipt.": "ደረሰኝዎን የሚያክሉበትን መንገድ ይምረጡ።",
  "Link": "አገናኝ", "QR": "QR ኮድ", "Image": "ምስል", "Parking": "ፓርኪንግ", "Paste a receipt link": "የደረሰኝ አገናኝ ለጥፍ",
  "Paste receipt link...": "የደረሰኝ አገናኝ እዚህ ለጥፍ…", "Scan from camera": "በካሜራ ቃኝ", "Read a screenshot": "ከምስል አንብብ",
  "Scan an Abrihot ticket": "የአብርሆት ቲኬት ቃኝ", "Abrihot Library": "አብርሆት ቤተ መጻሕፍት", "Abrihot": "አብርሆት",
  "Edit transaction": "ግብይት አስተካክል", "Add parking payment": "የፓርኪንግ ክፍያ ጨምር", "Review Receipt": "ደረሰኙን ይመልከቱ",
  "Approve & Save": "አረጋግጥና አስቀምጥ", "Save Changes": "ለውጦችን አስቀምጥ", "Scrape": "መረጃውን አምጣ", "Scrape Again": "እንደገና አምጣ",
  "Scraping receipt...": "ደረሰኙን በማንበብ ላይ…", "Back to receipt options": "ወደ ደረሰኝ አማራጮች ተመለስ", "Camera": "ካሜራ", "Zoom": "አቅርብ",
  "Preparing camera...": "ካሜራውን በማዘጋጀት ላይ…", "Choose receipt image": "የደረሰኝ ምስል ምረጥ", "Browse": "ምረጥ",
  "JPG, PNG or a screenshot": "JPG፣ PNG ወይም የስክሪን ምስል", "Use a clear image with the full receipt visible.": "ሙሉ ደረሰኙ የሚታይበትን ግልጽ ምስል ይጠቀሙ።",
  "is_withdraw": "የግብይት አይነት", "receipt_url": "የደረሰኝ አገናኝ", "created_at": "የተመዘገበበት ጊዜ", "date": "ቀን", "person": "ሰው", "amount": "መጠን",
  "MAKE IT YOURS": "እንደ ፍላጎትዎ", "A few useful controls, close at hand.": "ጠቃሚ ቅንብሮች በቅርብዎ።", "App preferences": "የመተግበሪያ ምርጫዎች",
  "For this device’s mobile app. Desktop stays the same.": "ለዚህ መሣሪያ መተግበሪያ ብቻ። የኮምፒውተር ማሳያው አይቀየርም።",
  "Calculator": "ማስያ", "Open calculator": "ማስያ ክፈት", "Close calculator": "ማስያ ዝጋ", "Show the calculator and table-total shortcut.": "ማስያውን እና የድምር አቋራጩን አሳይ።",
  "Compact transactions": "የታመቁ ግብይቶች", "Fit more transactions on your screen.": "ተጨማሪ ግብይቶችን በማያው ላይ አሳይ።",
  "Reduce motion": "እንቅስቃሴ ቀንስ", "Keep app transitions and buttons still.": "የመተግበሪያውን እና የአዝራሮቹን እንቅስቃሴ ቀንስ።",
  "People": "ሰዎች", "People in your transaction dropdowns. Changes are shared across the account.": "በግብይት ምርጫዎ ውስጥ ያሉ ሰዎች። ለውጦቹ ለመለያው ሁሉ ይተገበራሉ።",
  "Loading people…": "ሰዎችን በማምጣት ላይ…", "Add person": "ሰው ጨምር", "Add your first person below.": "የመጀመሪያውን ሰው ከታች ይጨምሩ።",
  "Name": "ስም", "Role": "ሚና", "(optional)": "(አማራጭ)", "Person’s name": "የሰውዬው ስም", "e.g. Site manager": "ለምሳሌ፦ የግንባታ ኃላፊ",
  "They will be available in transaction dropdowns.": "በግብይት ምርጫዎች ውስጥ ይጨመራሉ።", "They will leave the people list. Existing transactions will stay.": "ከሰዎች ዝርዝር ይወገዳሉ። ያሉት ግብይቶች ይቀጥላሉ።",
  "Refresh data": "መረጃ አድስ", "Refresh": "አድስ", "Refreshing…": "በማደስ ላይ…", "Get the latest transactions, balances and people.": "የቅርብ ጊዜ ግብይቶችን፣ ቀሪ ሂሳቦችን እና ሰዎችን አምጣ።",
  "Latest data loaded.": "የቅርብ ጊዜ መረጃ ተጭኗል።", "Use Refresh data below to retry.": "እንደገና ለመሞከር ከታች መረጃ አድስን ይጠቀሙ።",
  "Administrator": "አስተዳዳሪ", "Construction Manager": "የግንባታ ኃላፊ", "Project Coordinator": "የፕሮጀክት አስተባባሪ", "Finance Officer": "የፋይናንስ ኃላፊ", "Procurement Specialist": "የግዥ ባለሙያ", "Member": "አባል",
  "Bank accounts": "የባንክ ሂሳቦች", "Primary account": "ዋና ሂሳብ", "Apollo": "አፖሎ", "Apollo account": "የአፖሎ ሂሳብ", "Available balance": "ያለው ቀሪ ሂሳብ",
  "Last deposit": "የመጨረሻ ገቢ", "Show account values": "የሂሳብ መጠኖችን አሳይ", "Hide account values": "የሂሳብ መጠኖችን ደብቅ", "Hidden value": "የተደበቀ መጠን",
  "Apollo balance compared with regular balance": "የአፖሎ ሂሳብ ከዋናው ሂሳብ ጋር ያለው ልዩነት", "Difference": "ልዩነት", "Deficit": "ጉድለት", "Surplus": "ትርፍ", "Balanced": "እኩል",
  "Main bank card": "ዋና የባንክ ካርድ", "Apollo bank card": "የአፖሎ ባንክ ካርድ", "Apollo is locked": "አፖሎ ተቆልፏል", "Tap to unlock": "ለመክፈት ይንኩ",
  "Unlock to view your balance and latest activity.": "ቀሪ ሂሳብዎን እና የቅርብ ጊዜ ግብይቶችን ለማየት ይክፈቱ።", "Unlock Apollo": "አፖሎን ክፈት", "Unlock": "ክፈት",
  "Check latest": "የቅርብ ጊዜውን አረጋግጥ", "Check latest BOA SMS from Apollo": "የአፖሎን የቅርብ ጊዜ የባንክ መልእክት አረጋግጥ",
  "Comparing your latest BOA SMS with saved transactions.": "የቅርብ ጊዜ የባንክ መልእክትዎን ከተመዘገቡ ግብይቶች ጋር በማወዳደር ላይ።",
  "Your latest SMS is already saved.": "የቅርብ ጊዜ መልእክትዎ አስቀድሞ ተመዝግቧል።", "Select a person to add this transaction.": "ይህን ግብይት ለመጨመር ሰው ይምረጡ።",
  "Select person": "ሰው ምረጥ", "Later": "በኋላ", "Details": "ዝርዝሮች", "Edit narrative": "ማብራሪያ አስተካክል", "Sync your messages, then try again.": "መልእክቶችዎን አመሳስለው እንደገና ይሞክሩ።",
  "Summary": "ማጠቃለያ", "Interest": "ወለድ", "Balance analytics": "የሂሳብ ትንተና", "Month Summary": "የወር ማጠቃለያ", "Recent months": "የቅርብ ወራት",
  "Recent transactions": "የቅርብ ጊዜ ግብይቶች", "BOA SMS": "የባንክ መልእክቶች", "No BOA SMS transactions yet": "እስካሁን የባንክ መልእክት ግብይት የለም", "Waiting for last-month sync": "የባለፈውን ወር መረጃ በመጠባበቅ ላይ",
  "Credit interest": "የቁጠባ ወለድ", "Credit interest is locked": "የወለድ መረጃው ተቆልፏል", "Interest estimate": "የወለድ ግምት", "Estimated this month": "የዚህ ወር ግምት",
  "Show credit interest values": "የወለድ መጠኖችን አሳይ", "Hide credit interest values": "የወለድ መጠኖችን ደብቅ", "Interest period": "የወለድ ጊዜ", "Minimum balance": "ዝቅተኛው ቀሪ ሂሳብ",
  "Calculated from the lowest balance held during the month.": "በወሩ ውስጥ ከነበረው ዝቅተኛ ቀሪ ሂሳብ ይሰላል።", "Annual rate": "ዓመታዊ ምጣኔ", "Tax deduction": "የታክስ ቅናሽ", "Remaining estimate": "የቀረው ግምት", "Days remaining": "የቀሩ ቀናት",
  "Unlock Credit Interest": "የወለድ መረጃውን ክፈት", "Unlock to view your estimated earnings and calculation details.": "የወለድ ግምትዎን እና ዝርዝሩን ለማየት ይክፈቱ።", "from interest": "ከወለድ", "per year": "በዓመት",
  "Password": "የይለፍ ቃል", "Username": "የተጠቃሚ ስም", "Incorrect password": "የይለፍ ቃሉ ትክክል አይደለም", "Submit": "አስገባ", "Welcome Back": "እንኳን ደህና መጡ",
  "Enter your password to reveal the protected account details.": "የተጠበቀውን የሂሳብ መረጃ ለማየት የይለፍ ቃልዎን ያስገቡ።", "Close Apollo unlock": "የአፖሎ መክፈቻን ዝጋ", "Close interest unlock": "የወለድ መክፈቻን ዝጋ",
  "Locked": "ተቆልፏል", "Locked Out": "ለጊዜው ታግዷል", "Device Locked Out": "መሣሪያው ለጊዜው ታግዷል", "Locked out. Remaining time:": "ለጊዜው ታግዷል። የቀረው ጊዜ፦",
  "Houses": "ቤቶች", "Add house": "ቤት ጨምር", "Back to Houses": "ወደ ቤቶች ተመለስ", "Construction project": "የግንባታ ፕሮጀክት", "Project checklist": "የፕሮጀክት ማረጋገጫ ዝርዝር",
  "Edit name": "ስም አስተካክል", "Edit house": "ቤት አስተካክል", "House name...": "የቤቱ ስም…", "Delete house": "ቤት ሰርዝ", "Delete House?": "ቤቱ ይሰረዝ?",
  "No photo yet": "እስካሁን ፎቶ የለም", "Add photo": "ፎቶ ጨምር", "Add Photo": "ፎቶ ጨምር", "Replace photo": "ፎቶ ቀይር", "Full size": "ሙሉ መጠን",
  "Take a new picture or choose one from your gallery.": "አዲስ ፎቶ ያንሱ ወይም ከምስሎችዎ ይምረጡ።", "Overall progress": "አጠቃላይ ሂደት", "Money spent": "የወጣ ገንዘብ", "tasks completed": "ሥራዎች ተጠናቀዋል", "of": "ከ", "remaining": "ቀሪ",
  "Foundation": "መሠረት", "Building block / structure": "የሕንፃ አጥንት", "Shell": "ውጫዊ ክፍል", "Roofing": "ጣሪያ", "Exterior doors": "የውጭ በሮች", "Windows": "መስኮቶች",
  "Electrical": "ኤሌክትሪክ", "Electrical wiring & conduits": "የኤሌክትሪክ ሽቦና ቱቦ", "Electrical outlets & switches": "የኤሌክትሪክ መሰኪያና ማብሪያ", "Light fixtures & fittings": "የመብራት ዕቃዎች",
  "Interior": "የውስጥ ክፍል", "Gypsum board (drywall)": "ጂፕሰም ቦርድ", "Ceiling": "ኮርኒስ", "Ceramic floor tiles": "የወለል ሴራሚክ", "Interior doors": "የውስጥ በሮች", "Paint (interior)": "የውስጥ ቀለም",
  "Bathroom": "መታጠቢያ ክፍል", "Bathroom sink": "የመታጠቢያ እጅ መታጠቢያ", "WC / toilet": "መጸዳጃ", "Shower": "ሻወር", "Bathroom wall tiles": "የመታጠቢያ ግድግዳ ሴራሚክ", "Bathroom floor tiles": "የመታጠቢያ ወለል ሴራሚክ", "Bathroom accessories": "የመታጠቢያ መለዋወጫዎች",
  "Kitchen": "ወጥ ቤት", "Kitchen sink": "የወጥ ቤት እቃ ማጠቢያ", "Kitchen wall tiles": "የወጥ ቤት ግድግዳ ሴራሚክ", "Kitchen floor tiles": "የወጥ ቤት ወለል ሴራሚክ", "Kitchen cabinets & countertops": "የወጥ ቤት ቁም ሣጥኖችና ጠረጴዛዎች",
  "Final": "ማጠናቀቂያ", "Final clean & snag list": "የመጨረሻ ጽዳትና ማስተካከያ", "Construction visualizer": "የግንባታ ማሳያ", "Visualizer steps": "የማሳያ ደረጃዎች",
  "Build Shapes": "ቅርጾች አዘጋጅ", "2D plan": "2D ንድፍ", "3D view": "3D እይታ", "Tools": "መሣሪያዎች", "Rect": "አራት ማዕዘን", "Circle": "ክብ", "Triangle": "ሶስት ማዕዘን", "Curve": "ጠማማ", "Custom": "ብጁ",
  "Selected Wall": "የተመረጠ ግድግዳ", "Pick a wall on 2D": "በ2D ላይ ግድግዳ ምረጥ", "Wall Finish": "የግድግዳ ማጠናቀቂያ", "Floor": "ወለል", "Color": "ቀለም", "Floor image": "የወለል ምስል",
  "Camera texture": "በካሜራ ምስል", "Gallery texture": "ከምስሎች ምረጥ", "Use house photo": "የቤቱን ፎቶ ተጠቀም", "Gallery": "ምስሎች", "Uploading...": "በመጫን ላይ…",
  "Tap the grid to place a wall shape": "የግድግዳ ቅርጽ ለማስቀመጥ ንድፉን ይንኩ", "Add a shape in 2D first": "በመጀመሪያ በ2D ላይ ቅርጽ ይጨምሩ", "Empty plan": "ባዶ ንድፍ", "Visible walls": "የሚታዩ ግድግዳዎች",
  "Drag to look": "ለመመልከት ጎትት", "Pinch or wheel": "በጣት ወይም በመዳፊት አቅርብ", "Move": "ተንቀሳቀስ", "Look": "ተመልከት", "Close visualizer": "ማሳያውን ዝጋ",
  "Statistics": "ስታቲስቲክስ", "Spending Breakdown": "የወጪ ዝርዝር", "Spending by person": "ወጪ በሰዎች", "Share of outflow": "የወጪ ድርሻ", "% of outflow": "% የወጪ ድርሻ", "Outflow Breakdown": "የወጪ ትንተና",
  "is distributed across your team.": "በቡድንዎ ውስጥ ተከፋፍሏል።", "Total Inflow": "አጠቃላይ ገቢ", "Total Outflow": "አጠቃላይ ወጪ", "Net Balance": "የተጣራ ሂሳብ", "Tx Count": "የግብይት ብዛት", "Avg. Ticket Size": "አማካይ መጠን", "Largest Single Expense": "ትልቁ ወጪ",
  "Outflow History Curve": "የወጪ ታሪክ", "Monthly Spending Trend": "የወር ወጪ ሂደት", "No historical trend data available": "የቀድሞ ሂደት መረጃ የለም", "Category Distribution": "የምድብ ስርጭት", "No spending categories data available": "የወጪ ምድብ መረጃ የለም",
  "Other": "ሌላ", "Transfers": "ዝውውር", "Utilities": "የአገልግሎት ክፍያ", "Cash Withdrawals": "ጥሬ ገንዘብ ወጪ", "Food & Dining": "ምግብ", "Miscellaneous": "ልዩ ልዩ", "Spent": "የወጣ", "Amount Spent": "የወጣ መጠን",
  "Back to People": "ወደ ሰዎች ተመለስ", "Add New Person": "አዲስ ሰው ጨምር", "Add Person": "ሰው ጨምር", "+ Add Person": "+ ሰው ጨምር", "+ Add Payment": "+ ክፍያ ጨምር", "Add Parking": "ፓርኪንግ ጨምር",
  "Edit Profile": "መገለጫ አስተካክል", "Edit Profile Details": "የመገለጫ ዝርዝሮች አስተካክል", "Enter full name...": "ሙሉ ስም ያስገቡ…", "Enter name...": "ስም ያስገቡ…", "Enter role...": "ሚና ያስገቡ…", "e.g. Project Coordinator": "ለምሳሌ፦ የፕሮጀክት አስተባባሪ",
  "Transactions History": "የግብይት ታሪክ", "Total Payments Tracked": "አጠቃላይ የተመዘገቡ ክፍያዎች", "Parking Payments": "የፓርኪንግ ክፍያዎች", "Suqe Payments": "የሱቅ ክፍያዎች", "Suqe": "ሱቅ", "receipt transactions": "የደረሰኝ ግብይቶች", "parking payments": "የፓርኪንግ ክፍያዎች", "suqe payments": "የሱቅ ክፍያዎች",
  "Payment": "ክፍያ", "Amount (ETB)": "መጠን (ETB)", "Plate Number / Ref": "የታርጋ / የግብይት ቁጥር", "e.g. Code 3 - AA 12345": "ለምሳሌ፦ ኮድ 3 - AA 12345", "Shop / Grocery Name": "የሱቅ ስም", "e.g. Merkato Shop #2": "ለምሳሌ፦ መርካቶ ሱቅ ቁጥር 2", "Date and time": "ቀን እና ሰዓት", "Payment description...": "የክፍያ ማብራሪያ…", "Save Payment": "ክፍያ አስቀምጥ", "Adding...": "በማከል ላይ…",
  "Choose parking receipt source": "የፓርኪንግ ደረሰኝ ምንጭ ምረጥ", "Choose parking ticket from gallery": "የፓርኪንግ ቲኬት ከምስሎች ምረጥ", "Take parking ticket photo": "የፓርኪንግ ቲኬት ፎቶ አንሳ",
  "Take a ticket photo": "የቲኬት ፎቶ አንሳ", "Open your phone’s camera": "የስልክዎን ካሜራ ክፈት", "Choose from gallery": "ከምስሎች ምረጥ", "Use a photo you already have": "ያለዎትን ፎቶ ይጠቀሙ", "Reading ticket": "ቲኬቱን በማንበብ ላይ",
  "Parking saved": "ፓርኪንጉ ተመዝግቧል", "ETB added · Abrihot": "ETB ተጨምሯል · አብርሆት", "Scan ticket": "ቲኬት ቃኝ", "Enter duration": "ቆይታ አስገባ", "Check it against the ticket.": "ከቲኬቱ ጋር ያረጋግጡ።",
  "Entry time found.": "የመግቢያ ጊዜ ተገኝቷል።", "Ticket added": "ቲኬት ተጨምሯል", "See how": "አሰራሩን እይ", "Selected Abrihot parking ticket": "የተመረጠ የአብርሆት ፓርኪንግ ቲኬት", "Entry time": "የመግቢያ ሰዓት", "Time found. Date set to today—please check it.": "ሰዓቱ ተገኝቷል። ቀኑ የዛሬ ተደርጓል፤ እባክዎ ያረጋግጡ።",
  "Enter parking duration": "የፓርኪንግ ቆይታ አስገባ", "Enter how long the vehicle was parked.": "መኪናው ምን ያህል እንደቆየ ያስገቡ።", "Hours": "ሰዓታት", "Minutes": "ደቂቃዎች", "Choose another ticket": "ሌላ ቲኬት ምረጥ", "Parking duration": "የፓርኪንግ ቆይታ", "Parking total": "የፓርኪንግ ድምር", "Parking entry method": "የፓርኪንግ መግቢያ መንገድ", "Processing...": "በማዘጋጀት ላይ…", "ETB / started hour": "ETB / ለተጀመረ ሰዓት",
  "TRANSACTION DATE": "የግብይት ቀን", "Choose a date": "ቀን ምረጥ", "Choose transaction date": "የግብይት ቀን ምረጥ", "Close date picker": "የቀን ምርጫን ዝጋ", "Set date": "ቀን አስቀምጥ", "Today": "ዛሬ", "Day": "ቀን", "Month": "ወር", "Year": "ዓመት",
  "January": "ጃንዋሪ", "February": "ፌብሩዋሪ", "March": "ማርች", "April": "ኤፕሪል", "May": "ሜይ", "June": "ጁን", "July": "ጁላይ", "August": "ኦገስት", "September": "ሴፕቴምበር", "October": "ኦክቶበር", "November": "ኖቬምበር", "December": "ዲሴምበር",
  "Jan": "ጃን", "Feb": "ፌብ", "Mar": "ማር", "Apr": "ኤፕ", "Jun": "ጁን", "Jul": "ጁላይ", "Aug": "ኦገ", "Sep": "ሴፕ", "Oct": "ኦክ", "Nov": "ኖቬ", "Dec": "ዲሴ",
  "people": "ሰዎች", "new": "አዲስ", "-month view": "-ወር እይታ", "No deposit yet": "እስካሁን ገቢ የለም", "No earlier month available for comparison": "ለማወዳደር ቀደም ያለ ወር የለም",
  "First available Apollo balance point": "የመጀመሪያው የአፖሎ ሂሳብ መረጃ", "Spending": "ወጪ", "increased": "ጨምሯል", "decreased": "ቀንሷል", "compared with": "በማወዳደር", "by": "በ", "Error": "ስህተት", "AC": "አጽዳ", "Show": "አሳይ", "Hide": "ደብቅ",
  "Account update": "የሂሳብ ማደሻ", "Getting your latest bank data": "የቅርብ ጊዜ የባንክ መረጃዎን በማምጣት ላይ", "This may take a few seconds. This message will close automatically when your transactions arrive.": "ይህ ጥቂት ሰከንዶች ሊወስድ ይችላል። ግብይቶችዎ ሲመጡ ይህ መልእክት በራሱ ይዘጋል።", "Dismiss data update notification": "የመረጃ ማደሻ መልእክቱን ዝጋ",
  "Loading...": "በመጫን ላይ…", "Delete Transaction?": "ግብይቱ ይሰረዝ?", "This will remove": "ይህ ያስወግዳል", "from the database.": "ከመረጃ ቋቱ።", "and its checklist from the database.": "እና ዝርዝሩን ከመረጃ ቋቱ።", "Yes, Delete": "አዎ፣ ሰርዝ", "Deleting...": "በመሰረዝ ላይ…", "Scroll to top": "ወደ ላይ ተመለስ",
  "Receipt": "ደረሰኝ", "Receipt not found.": "ደረሰኙ አልተገኘም።", "Receipt unavailable.": "ደረሰኙ አይገኝም።", "Not recorded in the saved transaction": "በተመዘገበው ግብይት ውስጥ የለም", "Open the original bank receipt": "ዋናውን የባንክ ደረሰኝ ክፈት", "Scan the QR to open the bank receipt": "የባንክ ደረሰኙን ለመክፈት QR ኮዱን ይቃኙ", "Download PDF": "PDF አውርድ", "Saved transaction copy": "የተመዘገበ ግብይት ቅጂ", "View receipt": "ደረሰኝ እይ", "View": "እይ", "Try again": "እንደገና ሞክር", "Date": "ቀን", "Unknown": "ያልታወቀ",
  "Enter a name first.": "መጀመሪያ ስም ያስገቡ።", "Choose another name; this name is already used by a transaction filter.": "ሌላ ስም ይምረጡ፤ ይህ ስም ለግብይት ማጣሪያ ያገለግላል።", "This person is already in the list.": "ይህ ሰው አስቀድሞ በዝርዝሩ ውስጥ አለ።",
  "Could not save. Please try again.": "ማስቀመጥ አልተቻለም። እንደገና ይሞክሩ።", "Could not refresh all data. Check your connection and try again.": "መረጃውን ማደስ አልተቻለም። ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።", "People could not be loaded.": "የሰዎች ዝርዝር ማምጣት አልተቻለም።",
  "This person already exists. Refresh the list and try again.": "ይህ ሰው አስቀድሞ አለ። ዝርዝሩን አድሰው ይሞክሩ።", "Could not add this person. Refresh the list and try again.": "ይህን ሰው መጨመር አልተቻለም። ዝርዝሩን አድሰው ይሞክሩ።", "Could not remove this person. Refresh the list and try again.": "ይህን ሰው ማስወገድ አልተቻለም። ዝርዝሩን አድሰው ይሞክሩ።",
  "Your browser could not save preferences. They will last until you close the app.": "ምርጫዎቹን ማስቀመጥ አልተቻለም። መተግበሪያውን እስኪዘጉ ብቻ ይቆያሉ።", "added": "ተጨምሯል", "removed": "ተወግዷል",
  "Yes": "አዎ", "No": "አይ", "days": "ቀናት", "deg": "ዲግሪ", "Balance path": "የሂሳብ ሂደት", "Contactcenter": "የደንበኞች አገልግሎት", "Wall": "ግድግዳ", "Site manager": "የግንባታ ኃላፊ",
  "A person with this name already exists!": "በዚህ ስም ሰው አስቀድሞ አለ!", "An error occurred during delete.": "በመሰረዝ ጊዜ ስህተት ተፈጥሯል።", "An error occurred during save.": "በማስቀመጥ ጊዜ ስህተት ተፈጥሯል።", "An error occurred while adding person.": "ሰው በማከል ጊዜ ስህተት ተፈጥሯል።", "An error occurred while saving parking payment.": "የፓርኪንግ ክፍያ በማስቀመጥ ጊዜ ስህተት ተፈጥሯል።", "An error occurred while updating profile.": "መገለጫን በማደስ ጊዜ ስህተት ተፈጥሯል።",
  "Are you sure you want to delete this payment?": "ይህን ክፍያ ለመሰረዝ እርግጠኛ ነዎት?", "Are you sure you want to delete": "ይህን ለመሰረዝ እርግጠኛ ነዎት፦", "WARNING: This will permanently delete": "ማስጠንቀቂያ፦ ይህ በቋሚነት ይሰርዛል", "and decouple their tracked data. Are you ABSOLUTELY sure?": "እና የተመዘገበውን መረጃ ይለያል። እርግጠኛ ነዎት?",
  "Camera access is not available in this browser.": "በዚህ ማሰሻ ካሜራ መጠቀም አይቻልም።", "Camera permission was blocked or unavailable.": "የካሜራ ፍቃድ ታግዷል ወይም አይገኝም።", "Could not add house.": "ቤት መጨመር አልተቻለም።", "Could not delete house.": "ቤት መሰረዝ አልተቻለም።", "Could not load construction data.": "የግንባታ መረጃ ማምጣት አልተቻለም።", "Could not rename house.": "የቤቱን ስም መቀየር አልተቻለም።", "Could not update money spent.": "የወጣውን ገንዘብ ማደስ አልተቻለም።", "Could not upload photo.": "ፎቶ መጫን አልተቻለም።", "Could not download PDF. Please try again.": "PDF ማውረድ አልተቻለም። እንደገና ይሞክሩ።",
  "Could not read receipt details from this image. Try a clearer screenshot.": "ከዚህ ምስል የደረሰኝ መረጃ ማንበብ አልተቻለም። ግልጽ ምስል ይሞክሩ።", "Failed to add person to Supabase.": "ሰውን ማስቀመጥ አልተቻለም።", "Failed to delete payment from Supabase.": "ክፍያውን መሰረዝ አልተቻለም።", "Failed to delete person from Supabase.": "ሰውን ማስወገድ አልተቻለም።", "Failed to save parking payment to Supabase.": "የፓርኪንግ ክፍያ ማስቀመጥ አልተቻለም።", "Failed to save payment to Supabase.": "ክፍያውን ማስቀመጥ አልተቻለም።", "Failed to update profile details in Supabase.": "የመገለጫ ዝርዝሮችን ማደስ አልተቻለም።",
  "Image reading failed.": "ምስሉን ማንበብ አልተቻለም።", "Invalid Name!": "ስሙ ትክክል አይደለም!", "Opening camera...": "ካሜራውን በመክፈት ላይ…", "Paste or scan receipt link!": "የደረሰኝ አገናኝ ይለጥፉ ወይም ይቃኙ!", "Please fill in Name and Role!": "ስምና ሚና ያስገቡ!", "Please fill in amount and date fields!": "መጠንና ቀን ያስገቡ!", "Please fill in the amount and date!": "መጠንና ቀን ያስገቡ!",
  "Point the camera at the receipt QR code.": "ካሜራውን ወደ ደረሰኙ QR ኮድ ያመልክቱ።", "QR code was found, but it could not be converted to a receipt link.": "QR ኮድ ተገኝቷል፣ ግን ወደ ደረሰኝ አገናኝ መቀየር አልተቻለም።", "QR found. Scraping receipt...": "QR ተገኝቷል። ደረሰኙን በማንበብ ላይ…", "QR scanning is not supported in this browser.": "ይህ ማሰሻ QR መቃኘትን አይደግፍም።", "Reading image...": "ምስሉን በማንበብ ላይ…", "Scraping failed.": "መረጃውን ማምጣት አልተቻለም።", "Scraping failed": "መረጃውን ማምጣት አልተቻለም", "This QR contains a bank token, not a direct receipt link. Use Image OCR or paste the receipt link.": "ይህ QR የባንክ ኮድ ይዟል። የደረሰኝ ምስል ይጠቀሙ ወይም አገናኙን ይለጥፉ።", "This camera does not allow zoom changes.": "ይህ ካሜራ ማቅረብን መቀየር አይደግፍም።",
  "Could not compare transactions. Please try again.": "ግብይቶቹን ማወዳደር አልተቻለም። እንደገና ይሞክሩ።", "Could not check the latest BOA SMS. Please try again.": "የቅርብ ጊዜ የባንክ መልእክት ማረጋገጥ አልተቻለም። እንደገና ይሞክሩ።", "A newer BOA SMS is available. Check again before adding.": "አዲስ የባንክ መልእክት አለ። ከመጨመርዎ በፊት እንደገና ያረጋግጡ።", "Could not confirm the saved transaction. Check again before retrying.": "የተመዘገበውን ግብይት ማረጋገጥ አልተቻለም። እንደገና ከመሞከርዎ በፊት ያረጋግጡ።", "Could not add this transaction. Please try again.": "ይህን ግብይት መጨመር አልተቻለም። እንደገና ይሞክሩ።",
  "Could not open receipt image.": "የደረሰኝ ምስሉን መክፈት አልተቻለም።", "Could not prepare receipt image.": "የደረሰኝ ምስሉን ማዘጋጀት አልተቻለም።", "Update failed": "ማደስ አልተቻለም", "Save failed": "ማስቀመጥ አልተቻለም", "Save failed.": "ማስቀመጥ አልተቻለም።", "Delete failed": "መሰረዝ አልተቻለም", "Delete failed.": "መሰረዝ አልተቻለም።",
  "Transaction Date": "የግብይት ቀን", "Transaction Type": "የግብይት አይነት", "Transaction Reference": "የግብይት ቁጥር", "Payment Reference": "የክፍያ ቁጥር", "Bank Name": "የባንክ ስም", "Payer": "ከፋይ", "Payee": "ተከፋይ", "Sender": "ላኪ", "Receiver": "ተቀባይ", "Account Number": "የሂሳብ ቁጥር", "Transaction Amount": "የግብይት መጠን", "Total Amount": "ጠቅላላ መጠን",
  "No recent SMS": "የቅርብ ጊዜ መልእክት የለም",
  "Up to date": "ወቅታዊ ነው",
  "Couldn't check": "ማረጋገጥ አልተቻለም",
  "Latest transaction": "የቅርብ ጊዜ ግብይት",
  "Add narrative": "ማብራሪያ አስገባ",
  "Could not save this transaction. Please try again.": "ይህን ግብይት ማስቀመጥ አልተቻለም። እንደገና ይሞክሩ።",
  "No BOA SMS yet": "እስካሁን የባንክ መልእክት የለም",
  "Apollo balance trend locked": "የአፖሎ ሂሳብ ሂደት ተቆልፏል",
  "Apollo balance": "የአፖሎ ቀሪ ሂሳብ",
  "Spending was unchanged from": "ወጪው አልተለወጠም ከ",
  "Spending started after no withdrawals in": "ወጪ ተጀምሯል፤ ወጪ ያልነበረበት ወር፦",
  "Updated from BOA SMS": "ከባንክ መልእክት ተዘምኗል",
  "Unknown month": "ያልታወቀ ወር",
  "Reading the entry time...": "የመግቢያ ሰዓቱን በማንበብ ላይ…",
  "The photo could not be read. Try another photo.": "ፎቶውን ማንበብ አልተቻለም። ሌላ ፎቶ ይሞክሩ።",
  "Time not found. Try another photo.": "ሰዓቱ አልተገኘም። ሌላ ፎቶ ይሞክሩ።",
  "Upload failed": "መጫን አልተቻለም",
  "this house": "ይህ ቤት",
  "this transaction": "ይህ ግብይት",
  "AM": "ጠዋት",
  "PM": "ከሰዓት",
  "Source Account": "የላኪ ሂሳብ",
  "Source Account Name": "የላኪ ሂሳብ ስም",
  "Transferred amount": "የተላከ መጠን",
  "Converted Amount": "የተቀየረ መጠን",
  "Service Charge": "የአገልግሎት ክፍያ",
  "VAT (15%)": "ተጨማሪ እሴት ታክስ (15%)",
  "Receiver's Account": "የተቀባይ ሂሳብ",
  "Receiver's Name": "የተቀባይ ስም",
  "Phone Number": "ስልክ ቁጥር",
  "Account Transfer": "የሂሳብ ዝውውር",
  "Enter a valid receipt date and time.": "ትክክለኛ የደረሰኝ ቀንና ሰዓት ያስገቡ።",
  "The entry time is in the future. Check the scanned date.": "የመግቢያ ሰዓቱ ወደፊት ነው። የተቃኘውን ቀን ያረጋግጡ።",
  "Less than a minute": "ከአንድ ደቂቃ በታች",
  "min": "ደቂቃ",
  "hr": "ሰዓት",
  "hrs": "ሰዓታት",
  "Save endpoint is missing on the backend, and this draft was not auto-saved with an id.": "ይህን ግብይት ማስቀመጥ አልተቻለም።",
  "This device is locked out. Try again in": "ይህ መሣሪያ ታግዷል። እንደገና ይሞክሩ በ",
  "hours.": "ሰዓታት።",
  "Too many failed attempts. This device has been locked for 48 hours.": "ብዙ ያልተሳኩ ሙከራዎች። ይህ መሣሪያ ለ48 ሰዓታት ታግዷል።",
  "Incorrect password. Attempt": "የይለፍ ቃሉ ትክክል አይደለም። ሙከራ",
  "of 5. Device will lock after 5 failures.": "ከ5። ከ5 ያልተሳኩ ሙከራዎች በኋላ መሣሪያው ይታገዳል።",
  "Transactions could not be loaded.": "ግብይቶችን ማምጣት አልተቻለም።",
  "Supabase update policy is missing or this row is not visible for update.": "ይህን ግብይት ማደስ አልተቻለም።",
  "Supabase delete policy is missing or this row is not visible for delete.": "ይህን ግብይት መሰረዝ አልተቻለም።"
};
export default amharic;
